name: transformers_basic_train_env
channels:
  - defaults
dependencies:
  - python=3.7.11
  - pip=20.0
  - pip:
    - transformers==4.21.2
    - datasets==2.4.0
    - fire==0.4.0
    - torch==1.12.1
    - tensorboard==2.10.0
    - mlflow
    - azureml-mlflow